project:
  type: website
  output-dir: docs
  
website:
  title: "Shraddhesh Bhalerao"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true

editor: visual

