project:
  type: website
  output-dir: docs
  
website:
  title: "Shraddhesh Bhalerao"
  

  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: certifications/certificates.qmd
        text: Certifications
        
google-site-verification: NsbAdXXXyyhbPUML-RAXRhkbgt8stoPOTp47ISXGzQk


format:
  html:
    theme: cosmo
    css: custom.scss
    toc: true
    code-fold: false
    include-in-header: meta.html

editor: visual

